-- Netflix Project 
DROP TABLE IF EXISTS NETFLIX;

CREATE TABLE NETFLIX (
	SHOW_ID VARCHAR(7),
	TYPES VARCHAR(50),
	TITLE VARCHAR(150),
	DIRECTOR VARCHAR(255),
	CASTS VARCHAR(800),
	COUNTRY VARCHAR(150),
	DATE_ADDED VARCHAR(50),
	RELEASE_YEAR INT,
	RATING VARCHAR(10),
	DURATION VARCHAR(10),
	LISTED_IN VARCHAR(250),
	DESCRIPTION VARCHAR(250)
);